set_property SRC_FILE_INFO {cfile:C:/Users/ASUS/Documents/verilog_ecg/verilog_ecg.srcs/constrs_1/new/zedboard.xdc rfile:../../../verilog_ecg.srcs/constrs_1/new/zedboard.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y9       [get_ports clk]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P16      [get_ports rst_n]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U19      [get_ports uart_tx]
